apiVersion: v1
kind: Service
metadata:
  name: sc
  labels:
    app: sc
spec:
  ports:
    - port: 80
  selector:
    app: sc
    tier: frontend
  type: LoadBalancer
----
apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: sc-pv-claim
  labels:
    app: sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---