apiVersion: v1
kind: Service
metadata:
  name: sc-mysql
  labels:
    app: sc
spec:
  ports:
    - port: 3306
  selector:
    app: sc
    tier: mysql
  clusterIP: None
----
apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
----
