apiVersion: v1
kind: Service
metadata:
  name: sc-mysql
  labels:
    app: sc
spec:
  ports:
    - port: 3306
  selector:
    app: sc
    tier: mysql
  clusterIP: None
----
apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-mysql
  labels:
    app: sc
spec:
  selector:
    matchLabels:
      app: sc
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sc
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/sc_mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim